
spring:
  data:
    mongodb:
      username: ayush
      password: ayush
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

server:
  port: 8090


